common:
  mdm_version: mdm_working_set
  mdm_env: "qa"
  mdm_region: "us-west-2"
  cloudshellHelpFolder : "prod"
  dq_rule_integration_spark_driver_memory: "1G"
  dq_rule_integration_spark_executor_cores: 2
  dq_rule_integration_spark_executor_instances: 10
  dq_rule_integration_spark_executor_memory: "2G"
  dq_rule_integration_spark_max_concurrent_running_jobs: 5
  auto_add_partitions: false
  dsml_internal_host: "mlops-intcloud-mrel-pod1-internalelb.infacloudops.net"
  dsml_internal_port: "443"
  dsml_external_host: "qa-pod1-dsml.mrel.infaqa.com"
  dsml_external_port: "443"  
  cai_external_host: "pod1-cai.mrel.infaqa.com"
  cai_external_port: "443"
  cai_internal_host: "cai-qa-mrel-pod1-int-elb.infacloudops.net"
  cai_internal_port: "443"
  cdi_internal_host: "cdi-intcloud-mrel-pod1-internalelb.infacloudops.net"
  mdm_internal_host: "mdmnext-qa-mrel1.infacloudops.net"
  mdm_external_host: "qa-pod1-mdm.mrel.infaqa.com"
  dq_host: "dq-qa-pod1.mrel.infaqa.com"
  dis_host: "disn-qa-mrel-rt-int-elb.infacloudops.net"
  dis_batch_host: "disn-qa-mrel-int-elb.infacloudops.net"
  dockerRegistryCredentials: "mdmdeploybot,mdmdeploybot-ct"
  elastic_apm_enabled: false
  elasticsearch_cluster_name: "mdm_main_elasticsearch"
  elasticsearch_host: "mdm-es-http.${POD_ID}"
  elasticsearch_port: 9200
  iics_internal_host: "intcloud-mrel-pod1-internalelb.infacloudops.net"
  iics_internal_port: 443
  iics_ma_host: "qa-ma.mrel.infaqa.com"
  iics_pod_host: "qa-pod1.mrel.infaqa.com"
  jaeger_enabled: "false"
  jaeger_host: "mdm-jaeger-agent"
  jaeger_port: "6831"
  kube_api_namespace: "mdmnext-qa-mrel1ci3spark"
  kube_api_server: "k8s://https://kubernetes.default:443"
  kube_container_image_business_entity: business-entity-spark
  kube_container_image_index: search-index-spark
  kube_container_image_match_ng_index: match-ng-index-spark
  kube_container_image_match_ng_pair_gen: match-ng-pair-gen-spark
  kube_container_image_match_ng_training: match-ng-training-spark
  kube_container_image_dq_rule_integration: dq-rule-integration-spark
  kube_container_image_report_service: report-service-spark
  kube_container_image_egress: egress-spark
  mail_host: "mailqa-uswest2.cloudtrust.rocks"
  mail_port: 25
  mail_protocol: "smtp"
  mongodb_uri: "mongodb+srv://@username@:@password@@mdmnext-qa-mrel1ci3-blu.bvakf.mongodb.net/test?retryWrites=true&w=majority"
  mongodb_ssl_enabled: 1
  pki_mount_path: "pki/mdmnext-qaproduct1"
  pki_vault_role: "mdmnext-qaproduct1-us-west-2"
  vault_host: "vaultent.us.eksqa.cloudtrust.rocks"
  vault_port: 443
  vault_prefix: "kv/qa/mdmcloud/mdmnext/common/${POD_ID}"
  vault_protocol: "https"
  vault_role: "qa-mdmcloud-mdmnext"
  vault_ttl: "4h"
services: {}
